# -*- coding: utf-8 -*-
"""Salinan_dari_Template_Eksperimen_MSML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ttVA9a3br0-o9LbaEHFlY0wZMfNMgl48#scrollTo=6LJuq0GHu4NA
"""

import os
import re
import pandas as pd
import sys
import io
from sklearn.preprocessing import LabelEncoder
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

# CONFIG
DATA_PATH = "Eksperimen_SML_Hafiz-Satria\Analisis_sentimen_timnas_STY.csv"
OUTPUT_PATH = "Eksperimen_SML_Hafiz-Satria\preprocessing\Analisis_sentimen_timnas_STY_cleaned.csv"


# LOAD DATA
def load_data(path):
    print(" Loading dataset...")

    if not os.path.exists(path):
        raise FileNotFoundError(f"File tidak ditemukan: {path}")

    df = pd.read_csv(path)

    mapping = {'positif': 1, 'negatif': 0}
    df['label'] = df['label'].map(mapping)

    print(" Dataset loaded")
    print(f" Shape awal: {df.shape}")
    print(df.head())
    

    return df


# CLEAN TEXT
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


# PREPROCESSING
def preprocess(df):
    print("\n Preprocessing dimulai...")

    before = len(df)

    df = df.dropna().drop_duplicates()

    after = len(df)
    print(f" Data berkurang: {before} → {after}")

    # kolom
    text_col = df.columns[0]
    label_col = df.columns[-1]

    print(f" Text column : {text_col}")
    print(f" Label column: {label_col}")

    # cleaning
    df[text_col] = df[text_col].apply(clean_text)

    # encode label
    le = LabelEncoder()
    df[label_col] = le.fit_transform(df[label_col])

    # mapping label biar jelas
    label_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print("\n Label mapping:")
    print(label_mapping)

    # distribusi label
    print("\n Distribusi label:")
    print(df[label_col].value_counts())

    print("\n Preprocessing selesai")

    return df

# SAVE
def save_data(df, path):
    df.to_csv(path, index=False)
    print(f"\n Data saved: {path}")
    print(f" Final shape: {df.shape}")


# MAIN
def main():
    print(" START PIPELINE\n")

    df = load_data(DATA_PATH)
    df = preprocess(df)
    save_data(df, OUTPUT_PATH)

    print("\n DONE")

if __name__ == "__main__":
    main()
